version: '3.8'

services:

  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    container_name: 'web_prod'
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://hello_flask:hello_flask@films:5432/hello_flask_prod
      - SQL_HOST=films
      - SQL_PORT=5432
      - DATABASE=postgres
      - COMPOSE_PROJECT_NAME=prod_flask_app
    depends_on:
      - db


  db:
    image: postgres:13-alpine
    restart: always
    container_name: 'hello_flask_prod'
    hostname: film_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_flask
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=hello_flask_prod

  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    container_name: 'nginx_prod'
    depends_on:
      - web

volumes:
  postgres_data: